<?php

return [
    'vertical' => [
        [
            'url' => '/',
            'name' => 'Dashboard',
            'slug' => '/',
            'icon' => 'settings_input_svideo',
            'i18n' => 'Dashboard',
        ],
        [
            'url' => 'users',
            'name' => 'Users',
            'slug' => 'users',
            'icon' => 'face',
            'i18n' => 'Users',
        ],
        [
            'url' => 'wallets',
            'name' => 'Wallets',
            'class' => 'waves-effect waves-cyan',
            'slug' => 'wallets',
            'icon' => 'account_balance_wallet',
            'i18n' => 'Wallets',
        ],
        [
            'url' => 'accounts',
            'name' => 'Accounts',
            'class' => 'waves-effect waves-cyan',
            'slug' => 'accounts',
            'icon' => 'account_balance',
            'i18n' => 'Accounts',
        ],
        [
            'url' => 'money-flows',
            'name' => 'Money Flows',
            'class' => 'waves-effect waves-cyan',
            'slug' => 'money-flows',
            'icon' => 'import_export',
            'i18n' => 'Money Flows',
        ],
        [
            'url' => 'clients',
            'name' => 'Clients',
            'slug' => 'clients',
            'icon' => 'group',
            'i18n' => 'Clients',
        ],
        [
            'url' => 'contracts',
            'name' => 'Contracts',
            'slug' => 'contracts',
            'icon' => 'business_center',
            'i18n' => 'Contracts',
        ],
        [
            'url' => 'invoices',
            'name' => 'Invoices',
            'slug' => 'invoice',
            'icon' => 'receipt',
            'i18n' => 'Invoices',
        ],
        [
            'url' => 'list-incomes',
            'name' => 'Actual Income',
            'slug' => 'list-incomes',
            'icon' => 'attach_money',
            'i18n' => 'Actual Income',
        ],
        [
            'url' => 'incomes',
            'name' => 'Sales planning',
            'slug' => 'incomes',
            'icon' => 'attach_money',
            'i18n' => 'Sales planning',
        ],
        [
            'url' => 'expense-categories',
            'name' => 'Expense category',
            'slug' => 'category-expenses',
            'icon' => 'money_off',
            'i18n' => 'Expense category',
        ],
        [
            'url' => 'expenses',
            'name' => 'Expenses',
            'slug' => 'expenses',
            'icon' => 'money_off',
            'i18n' => 'Expenses',
        ],
        [
            'url' => 'people',
            'name' => 'People',
            'slug' => 'people',
            'icon' => 'people',
            'i18n' => 'People',
        ],
        [
            'url' => 'certifications',
            'name' => 'Certifications',
            'slug' => 'certifications',
            'icon' => 'school',
            'i18n' => 'school',
        ],
        [
            'url' => 'vacations',
            'name' => 'Vacations',
            'slug' => 'vacations',
            'icon' => 'weekend',
            'i18n' => 'Vacations',
        ],
        [
            'url' => 'bonuses',
            'name' => 'Bonuses',
            'slug' => 'bonuses',
            'icon' => 'monetization_on',
            'i18n' => 'monetization_on',
        ],
        [
            'url' => 'offers',
            'name' => 'Offers',
            'slug' => 'offers',
            'icon' => 'beenhere',
            'i18n' => 'beenhere',
        ],
        [
            'url' => 'salary-reviews',
            'name' => 'Salary Reviews',
            'slug' => 'salary-reviews',
            'icon' => 'local_atm',
            'i18n' => 'local_atm',
        ],
    ],
    'horizontal' => [
        //
    ]
];
